### ISSUE TITLE
Outcome field

### ISSUE THREAD

**Issue by stroup-tmu** [RobertWheel/Swing-Connect#1]
Robert, I see the issue: the enum field is just an array:

enum :outcome, [:win, :loss, :draw]

https://github.com/RobertWheel/Swing-Connect/blob/1f2e50c321a50f8fd39aa2bbb653da27c4e017fd/app/models/schedule.rb#L4C1-L4C56

**Comment by RobertWheel** [comment]
That worked, thank you so much!!!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: stroup-tmu ***@***.***>
Sent: Thursday, December 7, 2023 8:12:44 PM
To: RobertWheel/Swing-Connect ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RobertWheel/Swing-Connect] Outcome field (Issue #1)


Robert, I see the issue: the enum field is just an array:

enum :outcome, [:win, :loss, :draw]

https://github.com/RobertWheel/Swing-Connect/blob/1f2e50c321a50f8fd39aa2bbb653da27c4e017fd/app/models/schedule.rb#L4C1-L4C56

**Comment by stroup-tmu** [comment]
Great!
